

-- MySQL——>Oracle
-- VARCHAR ——>VARCHAR2
-- int(10) ——> INTEGER
-- PRIMARY KEY (ID),  ——> ALTER TABLE ACCOUNT_TBL ADD PRIMARY KEY (ID);
-- LOG_CREATED DATETIME NOT NULL,——> LOG_CREATED DATE DEFAULT SYSDATE NOT NULL ,
-- BIGINT(20) BIGINT可以用NUMBER(20,0)代替
-- BLOB BLOB
--  

DROP TABLE ACCOUNT_TBL;
CREATE TABLE ACCOUNT_TBL
(
    ID VARCHAR2(255) NOT NULL ,
    USER_ID VARCHAR2(255) DEFAULT NULL,
    MONEY   INTEGER   DEFAULT 0
) ;

ALTER TABLE ACCOUNT_TBL ADD PRIMARY KEY (ID);
-- CREATE UNIQUE INDEX ACCOUNT_TBL_KEY ON ACCOUNT_TBL (ID);
-- ;

INSERT INTO ACCOUNT_TBL (ID, USER_ID, MONEY)
VALUES (1, '1001', 10000);
INSERT INTO ACCOUNT_TBL (ID, USER_ID, MONEY)
VALUES (2, '1002', 10000);


CREATE TABLE UNDO_LOG (
  ID NUMBER(20,0) NOT NULL,
  BRANCH_ID NUMBER(20,0) NOT NULL,
  XID VARCHAR2(100) NOT NULL,
  CONTEXT VARCHAR2(128) NOT NULL,
  ROLLBACK_INFO BLOB NOT NULL,
  LOG_STATUS INTEGER NOT NULL,
  LOG_CREATED DATE DEFAULT SYSDATE NOT NULL ,
  LOG_MODIFIED DATE DEFAULT SYSDATE NOT NULL ,
  EXT VARCHAR2(100) DEFAULT NULL
) ;

ALTER TABLE UNDO_LOG ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX UNDO_LOG_KEY ON UNDO_LOG (XID,BRANCH_ID);
;

DROP TABLE ORDER_TBL;
CREATE TABLE ORDER_TBL
(
    ID VARCHAR2(255) NOT NULL ,
    USER_ID        VARCHAR2(255) DEFAULT NULL,
    COMMODITY_CODE VARCHAR2(255) DEFAULT NULL,
    COUNT          INTEGER      DEFAULT '0',
    MONEY          INTEGER      DEFAULT '0'
) 
;

ALTER TABLE ORDER_TBL ADD PRIMARY KEY (ID);
-- CREATE UNIQUE INDEX ORDER_TBL_KEY ON ORDER_TBL (ID);
-- ;


CREATE TABLE UNDO_LOG (
  ID NUMBER(20,0) NOT NULL,
  BRANCH_ID NUMBER(20,0) NOT NULL,
  XID VARCHAR2(100) NOT NULL,
  CONTEXT VARCHAR2(128) NOT NULL,
  ROLLBACK_INFO BLOB NOT NULL,
  LOG_STATUS INTEGER NOT NULL,
  LOG_CREATED DATE DEFAULT SYSDATE NOT NULL ,
  LOG_MODIFIED DATE DEFAULT SYSDATE NOT NULL ,
  EXT VARCHAR2(100) DEFAULT NULL
) ;

ALTER TABLE UNDO_LOG ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX UNDO_LOG_KEY ON UNDO_LOG (XID,BRANCH_ID);
;


DROP TABLE  STORAGE_TBL;
CREATE TABLE STORAGE_TBL
(
    ID VARCHAR2(255) NOT NULL ,
    COMMODITY_CODE VARCHAR2(255) DEFAULT NULL,
    COUNT          INTEGER      DEFAULT '0'
) ;

ALTER TABLE STORAGE_TBL ADD PRIMARY KEY (ID);
-- CREATE UNIQUE INDEX STORAGE_TBL_KEY ON STORAGE_TBL (ID);
;


INSERT INTO STORAGE_TBL (ID, COMMODITY_CODE, COUNT)
VALUES (1, '2001', 1000);

CREATE TABLE UNDO_LOG (
  ID NUMBER(20,0) NOT NULL,
  BRANCH_ID NUMBER(20,0) NOT NULL,
  XID VARCHAR2(100) NOT NULL,
  CONTEXT VARCHAR2(128) NOT NULL,
  ROLLBACK_INFO BLOB NOT NULL,
  LOG_STATUS INTEGER NOT NULL,
  LOG_CREATED DATE DEFAULT SYSDATE NOT NULL ,
  LOG_MODIFIED DATE DEFAULT SYSDATE NOT NULL ,
  EXT VARCHAR2(100) DEFAULT NULL
) ;

ALTER TABLE UNDO_LOG ADD PRIMARY KEY (ID);
CREATE UNIQUE INDEX UNDO_LOG_KEY ON UNDO_LOG (XID,BRANCH_ID);
;